import Head from 'next/head'
import Image from 'next/image'


import styles from '../styles/Home.module.css'


export default function Home() {
  return (
    <div className={styles.container}>
     
     <style jsx>
       {`
       h2{
         font-size: 38px;
       }
       h3{
        font-size: 28px;
      }
        
       `}
     </style>
      <Head>
        <title>Hunting coder</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      
      <main className={styles.main}>
        <h1 className={styles.title}>
         <span className='mySpan dummy'> Hunting Coder</span>
        
        </h1>
        <div className={styles.imgWrapper}>
        <Image className={styles.myImg} src='/1.jpg' height={158} width={237} />
        </div>
        <p className={styles.description}>
         A blog for hunting coders by a hunting coder
        </p>

       <div>
        
          <h2>Latest Blogs</h2>
          <div className='blogItem'>
        <h3>How to learn Javascript in 2022?</h3>
        <p>Javascript is a language used to design the web</p>
        </div>
        <div className='blogItem'>
        <h3>How to learn Javascript in 2022?</h3>
        <p>Javascript is a language used to design the web</p>
        </div>
        <div className='blogItem'>
        <h3>How to learn Javascript in 2022?</h3>
        <p>Javascript is a language used to design the web</p>
        </div>
       </div>
       
      </main>

      <footer className={styles.footer}>
       
      </footer>
    </div>
  )
}
